### ISSUE TITLE
"Welcome"-Screen: Add option to import Backups from previous Installations

### ISSUE THREAD

**Issue by EarthlingX** [cibersheep/linphone-simple#10]
When starting Linphone-Simple the first time a nice "_Welcome_"-screen appears.

It would be great if one could have an option to import backups from previous Linphone-installations, so it is not necessary anymore to type in all profile configurations manually by hand again.

Furthermore, an option in the settings would be great to export the user configs to a desired target path.

Thanks a lot for your efforts! :-)

**Comment by cibersheep** [comment]
Thanks!
I have copied your issue to Gitlab, we are not using Github anymore :)
https://gitlab.com/ubports-linphone/linphone-simple/issues/27
