### ISSUE TITLE
Remember to quit linphonec when closing app

### ISSUE THREAD

**Issue by cibersheep** [cibersheep/linphone-simple#3]
For now, tested that if in call an close app, call keeps on

**Comment by bhdouglass** [comment]
@cibersheep do we want to keep it running to allow us to receive calls? Maybe this bug should be to just terminate the current call?

**Comment by cibersheep** [comment]
Oh. You're absolutely right. We might have a 'quit' option in the app. Linphone has it.

**Comment by LarreaMikel** [comment]
@bhdouglass is right. We should add the call and terminate and see how this works. But the linphonec should keep running in the background. Maybe we can add something to disable it, but not when the app is closed.

**Comment by bhdouglass** [comment]
Agreed we should have running in the background a user configurable option.

**Comment by cibersheep** [comment]
Now, we have an small «commands text box». If `exit` is send to linphonecsh, we have no way to restart the service. 
So, should we quit linphone in another way?
Make a startService button?
